import type { CategorySlug, Project } from '~/models'
import { Category } from '~/models'

const categories: Record<CategorySlug, string> = {
  [Category.projects]: 'Projects',
  [Category.hobby]: 'Side projects',
  [Category.competition]: 'Competition & thesis',
  [Category.modules]: 'Packages & Modules',
  [Category.extensions]: 'Plugins, Scripts & Extensions',
  [Category.templates]: 'Templates',
  [Category.collections]: 'Collections',
}

const projects: Project[] = [
  {
    slug: 'wordware',
    name: 'Wordware',
    description: 'Sleek passphrase generator and wordlist manager',
    tags: ['Nuxt', 'TypeScript', 'Shadcn', 'Tailwind'],
    tagsPreview: ['Nuxt', 'ts', 'Shadcn', 'Tailwind'],
    timeframe: '2024',
    repo: 'https://github.com/matijaoe/wordware',
    url: 'https://wordware.vercel.app/',
    thumbnail: '/projects/wordware-dark.webp',
    categories: [Category.hobby],
    color: '#CD56DA',
  },
  {
    slug: 'fare',
    name: 'Fare',
    description: 'Application for tracking personal finances and attaining financial independence',
    tags: ['Nuxt', 'TypeScript', 'UnoCSS', 'Tanstack Query', 'Prisma', 'PlanetScale'],
    tagsPreview: ['Nuxt', 'ts', 'UnoCSS', 'Tanstack'],
    timeframe: '2022',
    repo: 'https://github.com/matijaoe/fare',
    thumbnail: '/projects/fare.webp',
    categories: [Category.competition],
    color: '#36D49A',
  },
  {
    slug: 'qwiz',
    name: 'Qwiz',
    description: 'Platform for creation, organization & discovery of pub quizzes',
    tags: ['Next', 'TypeScript', 'React Query', 'Mantine UI', 'Nest.js', 'Prisma', 'PlanetScale'],
    tagsPreview: ['Next', 'React Query', 'Nest', 'Prisma'],
    timeframe: '2022',
    repo: 'https://github.com/qwiz-app/qwiz',
    url: 'https://app.qwiz.party',
    thumbnail: '/projects/qwiz.webp',
    categories: [Category.competition],
    color: '#F4BD94',
  },
  {
    slug: 'aimo',
    name: 'Aimo',
    description: 'Social media platform connecting motivated individuals with accountability partners',
    tags: ['Nuxt', 'JavaScript', 'Vuex', 'Tailwind', 'Firebase'],
    tagsPreview: ['Nuxt', 'Tailwind', 'Firebase'],
    timeframe: '2021',
    repo: 'https://github.com/matijaoe/aimo',
    url: 'https://aimo.vercel.app',
    thumbnail: '/projects/aimo.webp',
    categories: [Category.competition],
    color: '#F5D765',
  },

  {
    slug: 'brutoneto',
    name: 'Brutoneto',
    description: 'Advanced salary calculation tools for Croatian employees. NPM module, API, Web App.',
    tags: ['TypeScript', 'Bun', 'Nuxt', 'Nitro', 'npm'],
    tagsPreview: ['ts', 'Bun', 'Nuxt', 'Nitro', 'npm'],
    timeframe: '2024—',
    url: 'https://brutoneto.matijao.com',
    repo: 'https://github.com/matijaoe/brutoneto',
    thumbnail: '/projects/brutoneto.webp',
    color: '#FCC800',
    categories: [Category.hobby],
  },
  {
    slug: 'aged',
    name: 'Aged',
    description: 'Encrypt and decrypt files with age, entirely in your browser. Compatible with the age CLI.',
    tags: ['React', 'TypeScript', 'Base UI', 'Tailwind', 'Vite'],
    tagsPreview: ['React', 'ts', 'Base UI', 'Tailwind'],
    timeframe: '2026',
    repo: 'https://github.com/matijaoe/aged',
    url: 'https://aged-iota.vercel.app',
    categories: [Category.hobby],
  },
  {
    slug: 'plum',
    name: 'Plum',
    description: 'Reader mode app & browser extension. Load any article URL and get a clean, distraction-free view.',
    tags: ['React', 'TypeScript', 'Tailwind', 'WXT'],
    tagsPreview: ['React', 'ts', 'Tailwind', 'WXT'],
    timeframe: '2026',
    repo: 'https://github.com/matijaoe/plum',
    url: 'https://plum.matijao.com',
    categories: [Category.hobby],
    wip: true,
  },
  {
    slug: 'bip39-lookup',
    name: 'BIP39 lookup',
    description: 'BIP39 word lookup tool',
    tags: ['SvelteKit', 'TypeScript', 'Tailwind', 'bitcoin'],
    tagsPreview: ['svelte', 'ts', 'Tailwind', 'bitcoin'],
    timeframe: '2022',
    repo: 'https://github.com/matijaoe/bip39-lookup',
    url: 'https://bip39-rosy.vercel.app',
    thumbnail: '/projects/btc-tools.webp',
    categories: [Category.hobby],
    color: '#F97315',
  },
  {
    slug: 'bit-complete',
    name: 'Bit Complete',
    description: 'Tool for generating a valid 24th word for a BIP39 seed phrase',
    tags: ['Vue', 'TypeScript', 'Pico CSS', 'bitcoin'],
    tagsPreview: ['Vue', 'ts', 'Pico CSS', 'bitcoin'],
    timeframe: '2024',
    repo: 'https://github.com/matijaoe/seed-finisher',
    url: 'https://seed-finisher.vercel.app/',
    thumbnail: '/projects/bit-complete.webp',
    categories: [Category.hobby],
    color: '#027FC0',
  },
  {
    slug: 'bitcoin-ticker',
    name: 'Bitcoin Ticker',
    description: 'Real-time Bitcoin price tracker pulling data from multiple exchanges via WebSockets',
    tags: ['Vue', 'Tailwind', 'bitcoin'],
    timeframe: '2024',
    repo: 'https://github.com/matijaoe/bitcoin-ticker',
    url: 'https://bitcoin-ticker-seven.vercel.app/',
    thumbnail: '/projects/bitcoin-ticker.webp',
    categories: [Category.hobby],
    color: '#F97315',
  },
  {
    slug: 'emojito',
    name: 'Emojito',
    description: 'Encode text into emojis using Unicode steganography',
    tags: ['Python'],
    timeframe: '2025',
    repo: 'https://github.com/matijaoe/emojito',
    url: 'https://pypi.org/project/emojito-py/',
    categories: [Category.hobby],
  },
  {
    slug: 'xpub-derive',
    name: 'xpub-derive',
    description: 'CLI tool for deriving bitcoin addresses',
    tags: ['TypeScript', 'Bun', 'Bitcoin'],
    timeframe: '2025',
    repo: 'https://github.com/matijaoe/xpub-derive',
    categories: [Category.hobby],
  },
  {
    slug: 'favicones',
    name: 'Favicônes',
    description: 'Quick and easy way to use any icon as favicon',
    tags: ['Nuxt', 'UnoCSS', 'iconify'],
    timeframe: '2022',
    repo: 'https://github.com/matijaoe/favicones',
    url: 'https://favicones.vercel.app/',
    thumbnail: '/projects/favicones.webp',
    categories: [Category.hobby],
    color: '#EA580B',
  },
  {
    slug: 'utilipea',
    name: 'Utilipea',
    description: 'Yet another utility library',
    tags: ['TypeScript', 'Bun', 'Vitest', 'npm'],
    tagsPreview: ['ts', 'Bun', 'Vitest', 'npm'],
    timeframe: '2023/24',
    repo: 'https://github.com/matijaoe/utilipea',
    categories: [Category.modules],
    color: '#A8B1FF',
  },
  {
    slug: 'vue-ecosystem-snippets',
    name: 'Vue Ecosystem Snippets',
    description: 'Snippets for the modern Vue ecosystem',
    timeframe: '2023',
    url: 'https://marketplace.visualstudio.com/items?itemName=matijao.vue-nuxt-snippets',
    repo: 'https://github.com/mat2ja/vue-ecosystem-snippets',
    thumbnail: '/projects/vue-ecosystem-snippets.png',
    tags: ['Deno', 'TypeScript', 'VSCode'],
    tagsPreview: ['Deno', 'ts', 'VSCode'],
    categories: [Category.extensions],
    color: '#1FBE4B',
  },
  {
    slug: 'modern-javascript-snippets',
    name: 'Modern JavaScript Snippets',
    description: 'Code snippets for modern JavaScript & TypeScript',
    timeframe: '2023',
    url: 'https://marketplace.visualstudio.com/items?itemName=matijao.modern-js-snippets',
    repo: 'https://github.com/mat2ja/modern-javascript-snippets',
    thumbnail: '/projects/modern-javascript-snippets.png',
    tags: ['Deno', 'TypeScript', 'VSCode'],
    tagsPreview: ['Deno', 'ts', 'VSCode'],
    categories: [Category.extensions],
    color: '#E8D44D',
  },
  {
    slug: 'url-query-editor',
    name: 'URL Query Editor',
    description: 'Simple but powerful Chrome extension for editing URL query parameters',
    timeframe: '2023',
    repo: 'https://github.com/matijaoe/url-query-editor',
    thumbnail: '/projects/url-query-editor.webp',
    tags: ['Svelte', 'Tailwind', 'Chromium'],
    categories: [Category.extensions],
    color: '#17B7A6',
  },
  {
    slug: 'pnpm-plugin-zsh',
    name: 'pnpm.plugin.zsh',
    description: 'Oh My Zsh aliases for common pnpm commands',
    timeframe: '2023',
    repo: 'https://github.com/matijaoe/pnpm.plugin.zsh',
    tags: ['Zsh', 'pnpm'],
    categories: [Category.extensions],
  },
  {
    slug: 'cage-plugin-zsh',
    name: 'cage.plugin.zsh',
    description: 'One command for age. Encrypts plain files, decrypts age files, no flags.',
    timeframe: '2026',
    repo: 'https://github.com/matijaoe/cage.plugin.zsh',
    tags: ['Zsh', 'age'],
    categories: [Category.extensions],
  },
  {
    slug: 'audible-hq-cover',
    name: 'Audible HQ Cover',
    description: 'Userscript for obtaining full-res Audible covers',
    timeframe: '2024',
    repo: 'https://github.com/matijaoe/audible-hq-cover',
    url: 'https://greasyfork.org/en/scripts/511910-audible-hq-cover',
    tags: ['js'],
    categories: [Category.extensions],
    color: '#0CBDF0',

  },
  {
    slug: 'nuxt-starter',
    name: 'Nuxt Uno Starter',
    description: 'Nuxt 3 & UnoCSS starter template',
    timeframe: '2023',
    repo: 'https://github.com/matijaoe/nuxt-starter',
    url: 'https://the-nuxt-starter.vercel.app/',
    thumbnail: '/projects/nuxt-starter.png',
    tags: ['Nuxt', 'UnoCSS'],
    categories: [Category.templates],
    color: '#01DC82',
  },
  {
    slug: 'vue-starter',
    name: 'Vue Uno Starter',
    description: 'Vue & UnoCSS starter template',
    timeframe: '2023',
    repo: 'https://github.com/matijaoe/vue-starter',
    url: 'https://vue-uno-starter.vercel.app/',
    thumbnail: '/projects/vue-starter.webp',
    tags: ['Vue', 'UnoCSS'],
    categories: [Category.templates],
    color: '#079669',
  },
  {
    slug: 'advent-of-code-template',
    name: 'AoC Template',
    description: 'Automated Advent of Code Template',
    timeframe: '2023',
    repo: 'https://github.com/matijaoe/advent-of-code',
    tags: ['Bun', 'TypeScript'],
    tagsPreview: ['Bun', 'ts'],
    categories: [Category.templates],
  },
  {
    slug: 'vue-anu-starter',
    name: 'Vue & Anu Starter',
    description: 'Vue & Anu starter template',
    timeframe: '2023',
    repo: 'https://github.com/matijaoe/vue-anu-starter',
    url: 'https://vue-anu-starter.vercel.app/',
    tags: ['Vue', 'UnoCSS'],
    categories: [Category.templates],
  },
  {
    slug: 'bip39-wordlist',
    name: 'BIP39 Wordlists',
    description: ' Collection of English BIP39 wordlists in various formats for practical use',
    timeframe: '2024—',
    repo: 'https://github.com/matijaoe/bip39-wordlist',
    tags: ['json', 'bitcoin'],
    categories: [Category.collections],
  },
  {
    slug: 'bitcoin-books',
    name: 'Bitcoin Books',
    description: 'Curated Notion database of Bitcoin books with rich metadata and reference links',
    timeframe: '2025—',
    url: 'https://seasoned-trader-815.notion.site/16313affa9c780d9a6dede8dc01c61d0?v=7810fd9ff53f41908faf81cc36476562',
    tags: ['notion', 'bitcoin'],
    categories: [Category.collections],
  },
]

export const useProjects = () => {
  const uniqueCategories = computed(() => {
    const categorySet = new Set<CategorySlug>()
    projects.forEach((project) => {
      project.categories.forEach((category) => {
        categorySet.add(category)
      })
    })

    return Array.from(categorySet).map((category) => {
      return {
        label: categories[category],
        value: category,
      }
    })
  })

  const getProduct = (slug: string): Project | undefined => {
    return projects.find((project) => project.slug === slug)
  }

  const getProjectsByCategory = (category: CategorySlug): Project[] => {
    return projects.filter((project) => project.categories.includes(category))
  }

  return {
    projects,
    getProduct,
    getProjectsByCategory,
    uniqueCategories,
  }
}
